# Cloud Build configuration for automatic deployment to Cloud Run
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tldrcontent:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tldrcontent:latest'
      - '.'
    dir: 'web'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tldrcontent:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tldrcontent:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tldrcontent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tldrcontent:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '60s'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/tldrcontent:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/tldrcontent:latest'

# Build timeout
timeout: '1200s'

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
